#!/usr/bin/env python3
"""AuraCode Lightweight AST Mutation Engine.

Detects vitiated oracles and vacuous test suites generated by LLMs by introducing
deterministic syntactic mutations into production code and executing tests.
If tests pass despite logic alterations, the test suite is flagged as a vitiated oracle.
Zero external runtime dependencies (Pure Python Standard Library: ast, subprocess, tempfile).
"""

import ast
import copy
import json
import os
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import List, Tuple, Optional, Dict, Any, Set

from tools.assurance_result import build_result


def _attach_canonical_result(result: Dict[str, Any], target_file: Path) -> Dict[str, Any]:
    """Attach a canonical shadow-mode result without changing legacy mutation status."""
    legacy_status = result.get("status")
    total_mutants = int(result.get("total_mutants", 0) or 0)
    survived = int(result.get("survived", 0) or 0)
    timed_out = int(result.get("timeouts", 0) or 0)
    evaluator_errors = int(result.get("errors", 0) or 0)

    if legacy_status == "ERROR":
        canonical_status = "ERROR"
        reason = str(result.get("message") or "Mutation evaluator failed; assurance cannot advance.")
    elif total_mutants == 0:
        canonical_status = "NOT_APPLICABLE"
        reason = "No mutable AST sites were found; mutation evidence was not produced."
    elif timed_out > 0 or evaluator_errors > 0:
        canonical_status = "ERROR"
        reason = "One or more mutation evaluations timed out or failed."
    elif survived > 0:
        canonical_status = "INCONCLUSIVE"
        reason = f"{survived} mutant(s) survived; the suite did not distinguish all evaluated mutations."
    else:
        canonical_status = "PASS"
        reason = "All evaluated mutants were killed by the test suite."

    findings = [
        item for item in result.get("mutants", [])
        if isinstance(item, dict) and item.get("status") != "KILLED"
    ]

    enriched = dict(result)
    enriched["canonical_result"] = build_result(
        check_id="mutation",
        status=canonical_status,
        producer_tool="mutation_engine",
        producer_method="python_ast_mutation",
        workspace=str(target_file.parent),
        reason=reason,
        scope={"files_scanned": 1, "languages": ["python"]},
        findings=findings,
        legacy={
            "source": "tools/mutation_engine.py",
            "source_status": legacy_status,
            "mutation_score": result.get("mutation_score"),
        },
    )
    return enriched


@dataclass
class Mutant:
    """Represents a discrete syntactic code mutation."""
    mutant_id: int
    line_number: int
    mutation_type: str
    original_op: str
    mutated_op: str
    mutated_code: str
    status: str = "PENDING"
    error_output: Optional[str] = None
    criticality: str = "NORMAL"
    security_relevant: bool = False
    disposition_reason: Optional[str] = None


MUTANT_STATUSES = {
    "PENDING",
    "KILLED",
    "SURVIVED",
    "NO_COVERAGE",
    "TIMEOUT",
    "ERROR",
    "LIKELY_EQUIVALENT",
    "WAIVED",
}

_SECURITY_GUARD_KEYWORDS = {
    "AUTHORIZATION": ("authorized", "authorization", "authz", "permission", "role", "can_access", "is_admin"),
    "AUTHENTICATION": ("authenticated", "authentication", "login", "session", "is_authenticated"),
    "TENANCY": ("tenant", "organization_id", "org_id", "company_id", "account_id"),
    "CSRF": ("csrf",),
    "RATE_LIMIT": ("rate_limit", "rate_limited", "throttle", "too_many_requests"),
    "SIGNATURE": ("signature", "verify_signature", "hmac"),
    "EXPIRATION": ("expired", "expiry", "expires", "expiration"),
}

_BUSINESS_GUARD_KEYWORDS = (
    "balance",
    "amount",
    "inventory",
    "stock",
    "quota",
    "state",
    "status",
    "transition",
)

_SANITIZER_KEYWORDS = ("sanitize", "sanitise", "escape_html", "escape_sql", "scrub", "clean_input")


def _call_name(node: ast.AST) -> str:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        prefix = _call_name(node.value)
        return f"{prefix}.{node.attr}" if prefix else node.attr
    return ""


def _guard_body_rejects(body: List[ast.stmt]) -> bool:
    for stmt in body:
        if isinstance(stmt, ast.Raise):
            return True
        if isinstance(stmt, ast.Return):
            value = stmt.value
            if value is None:
                return True
            if isinstance(value, ast.Constant):
                if value.value in {False, None, 401, 403, 429}:
                    return True
                if isinstance(value.value, str) and value.value.lower() in {
                    "denied", "forbidden", "unauthorized", "invalid"
                }:
                    return True
    return False


def _guard_mutation_type(node: ast.If) -> Optional[str]:
    if not _guard_body_rejects(node.body):
        return None
    try:
        text = ast.unparse(node.test).lower()
    except Exception:
        return None

    for category, keywords in _SECURITY_GUARD_KEYWORDS.items():
        if any(keyword in text for keyword in keywords):
            return f"SECURITY_{category}_GUARD_BYPASS"
    if any(keyword in text for keyword in _BUSINESS_GUARD_KEYWORDS):
        return "BUSINESS_INVARIANT_GUARD_BYPASS"
    return None


def _mutant_metadata(mutation_type: str) -> Tuple[str, bool]:
    if mutation_type.startswith("SECURITY_"):
        return "CRITICAL", True
    if mutation_type in {"BUSINESS_INVARIANT_GUARD_BYPASS", "EXCEPTION_SUPPRESSION"}:
        return "HIGH", False
    return "NORMAL", False


class ASTMutantGenerator(ast.NodeTransformer):
    """Generates discrete mutants from a Python AST."""

    # Relational operator mappings
    RELATIONAL_MAP = {
        ast.Gt: ast.LtE,
        ast.Lt: ast.GtE,
        ast.GtE: ast.Lt,
        ast.LtE: ast.Gt,
        ast.Eq: ast.NotEq,
        ast.NotEq: ast.Eq,
    }

    # Arithmetic operator mappings
    ARITHMETIC_MAP = {
        ast.Add: ast.Sub,
        ast.Sub: ast.Add,
        ast.Mult: ast.FloorDiv,
    }

    # Boolean operator mappings
    BOOLOP_MAP = {
        ast.And: ast.Or,
        ast.Or: ast.And,
    }

    def __init__(self, target_node_index: int = -1):
        super().__init__()
        self.target_node_index = target_node_index
        self.current_index = 0
        self.mutated = False
        self.recorded_mutation: Optional[Tuple[int, str, str, str]] = None

    def visit_If(self, node: ast.If) -> ast.AST:
        guard_type = _guard_mutation_type(node)
        mutation_type = guard_type or "FLOW_CONDITION_NEGATION"
        if self.current_index == self.target_node_index:
            original = ast.unparse(node.test) if hasattr(ast, "unparse") else "condition"
            if guard_type:
                node.test = ast.Constant(value=False)
                mutated = "False"
            else:
                node.test = ast.UnaryOp(op=ast.Not(), operand=node.test)
                mutated = f"not ({original})"
            self.mutated = True
            self.recorded_mutation = (
                node.lineno,
                mutation_type,
                original,
                mutated,
            )
        self.current_index += 1
        return self.generic_visit(node)

    def visit_Raise(self, node: ast.Raise) -> ast.AST:
        if self.current_index == self.target_node_index:
            original = ast.unparse(node) if hasattr(ast, "unparse") else "raise"
            replacement = ast.copy_location(ast.Pass(), node)
            self.mutated = True
            self.recorded_mutation = (
                node.lineno,
                "EXCEPTION_SUPPRESSION",
                original,
                "pass",
            )
            self.current_index += 1
            return replacement
        self.current_index += 1
        return self.generic_visit(node)

    def visit_Expr(self, node: ast.Expr) -> ast.AST:
        if isinstance(node.value, ast.Call):
            if self.current_index == self.target_node_index:
                original = ast.unparse(node) if hasattr(ast, "unparse") else "call"
                replacement = ast.copy_location(ast.Pass(), node)
                self.mutated = True
                self.recorded_mutation = (
                    node.lineno,
                    "STATEMENT_DELETION",
                    original,
                    "pass",
                )
                self.current_index += 1
                return replacement
            self.current_index += 1
        return self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> ast.AST:
        call_name = _call_name(node.func).lower()
        if node.args and any(keyword in call_name for keyword in _SANITIZER_KEYWORDS):
            if self.current_index == self.target_node_index:
                original = ast.unparse(node) if hasattr(ast, "unparse") else call_name
                replacement = ast.copy_location(copy.deepcopy(node.args[0]), node)
                self.mutated = True
                self.recorded_mutation = (
                    getattr(node, "lineno", 0),
                    "SECURITY_SANITIZER_REMOVAL",
                    original,
                    ast.unparse(replacement) if hasattr(ast, "unparse") else "raw_input",
                )
                self.current_index += 1
                return replacement
            self.current_index += 1
        return self.generic_visit(node)

    def visit_Compare(self, node: ast.Compare) -> ast.AST:
        new_ops = []
        for op in node.ops:
            op_type = type(op)
            if op_type in self.RELATIONAL_MAP:
                if self.current_index == self.target_node_index:
                    new_op_cls = self.RELATIONAL_MAP[op_type]
                    new_ops.append(new_op_cls())
                    self.mutated = True
                    self.recorded_mutation = (
                        node.lineno,
                        "RELATIONAL",
                        op_type.__name__,
                        new_op_cls.__name__
                    )
                else:
                    new_ops.append(op)
                self.current_index += 1
            else:
                new_ops.append(op)
        node.ops = new_ops
        return self.generic_visit(node)

    def visit_BinOp(self, node: ast.BinOp) -> ast.AST:
        op_type = type(node.op)
        if op_type in self.ARITHMETIC_MAP:
            if self.current_index == self.target_node_index:
                new_op_cls = self.ARITHMETIC_MAP[op_type]
                node.op = new_op_cls()
                self.mutated = True
                self.recorded_mutation = (
                    node.lineno,
                    "ARITHMETIC",
                    op_type.__name__,
                    new_op_cls.__name__
                )
            self.current_index += 1
        return self.generic_visit(node)

    def visit_BoolOp(self, node: ast.BoolOp) -> ast.AST:
        op_type = type(node.op)
        if op_type in self.BOOLOP_MAP:
            if self.current_index == self.target_node_index:
                new_op_cls = self.BOOLOP_MAP[op_type]
                node.op = new_op_cls()
                self.mutated = True
                self.recorded_mutation = (
                    node.lineno,
                    "LOGICAL",
                    op_type.__name__,
                    new_op_cls.__name__
                )
            self.current_index += 1
        return self.generic_visit(node)

    def visit_Constant(self, node: ast.Constant) -> ast.AST:
        if isinstance(node.value, bool):
            if self.current_index == self.target_node_index:
                node.value = not node.value
                self.mutated = True
                self.recorded_mutation = (
                    node.lineno,
                    "BOOLEAN_CONSTANT",
                    str(not node.value),
                    str(node.value)
                )
            self.current_index += 1
        return node

    def visit_Return(self, node: ast.Return) -> ast.AST:
        if node.value is not None and not (isinstance(node.value, ast.Constant) and node.value.value is None):
            if self.current_index == self.target_node_index:
                original_repr = ast.unparse(node.value) if hasattr(ast, "unparse") else "expr"
                node.value = ast.Constant(value=None)
                self.mutated = True
                self.recorded_mutation = (
                    node.lineno,
                    "RETURN_NULLIFICATION",
                    original_repr,
                    "None"
                )
            self.current_index += 1
        return self.generic_visit(node)


def generate_mutants_for_source(source_code: str, max_mutants: int = 25) -> List[Mutant]:
    """Parse source code and generate up to max_mutants discrete syntactic mutants."""
    try:
        base_tree = ast.parse(source_code)
    except SyntaxError:
        return []

    # Count total mutable locations
    counter = ASTMutantGenerator(target_node_index=-1)
    counter.visit(copy.deepcopy(base_tree))
    total_sites = counter.current_index

    mutants = []
    step = max(1, total_sites // max_mutants) if total_sites > max_mutants else 1
    selected_indices = list(range(0, total_sites, step))[:max_mutants]

    for m_id, idx in enumerate(selected_indices, start=1):
        mut_gen = ASTMutantGenerator(target_node_index=idx)
        mut_tree = mut_gen.visit(copy.deepcopy(base_tree))
        if mut_gen.mutated and mut_gen.recorded_mutation:
            line_no, m_type, orig_op, new_op = mut_gen.recorded_mutation
            try:
                mut_code = ast.unparse(mut_tree)
            except AttributeError:
                # Python < 3.9 fallback
                continue

            criticality, security_relevant = _mutant_metadata(m_type)
            mutants.append(Mutant(
                mutant_id=m_id,
                line_number=line_no,
                mutation_type=m_type,
                original_op=orig_op,
                mutated_op=new_op,
                mutated_code=mut_code,
                criticality=criticality,
                security_relevant=security_relevant,
            ))

    return mutants


def find_enclosing_function_name(tree: Optional[ast.AST], target_line: int) -> Optional[str]:
    """Find the function or method enclosing a given line number."""
    if not tree:
        return None
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            start = getattr(node, "lineno", 0)
            end = getattr(node, "end_lineno", start + 100)
            if start <= target_line <= end:
                return node.name
    return None


def generate_remediation_prescription(
    mutant: Mutant,
    source_line: str,
    enclosing_func: Optional[str] = None
) -> Dict[str, Any]:
    """Generate prescriptive plain-language diagnosis, analogy, and test snippet."""
    m_type = mutant.mutation_type
    func_target = enclosing_func if enclosing_func else "target_function"
    clean_src = source_line.strip()

    if m_type == "RELATIONAL":
        diagnosis = (
            f"O teste atual não valida o caminho alternativo da condição na linha {mutant.line_number}. "
            f"A inversão do operador '{mutant.original_op}' para '{mutant.mutated_op}' continuou passando verde."
        )
        missing_scenario = (
            f"Falta um teste com entrada que force a condição '{clean_src}' a avaliar para o resultado oposto "
            f"(cenário de contorno ou negação da regra)."
        )
        analogy = (
            "É como testar uma catraca de metrô passando apenas com o cartão válido, "
            "sem testar se a catraca realmente bloqueia quem tenta passar sem pagar."
        )
        test_snippet = (
            f"def test_{func_target}_boundary_condition(self):\n"
            f"    # Cenário de contorno para matar mutante na linha {mutant.line_number}\n"
            f"    # Valide o comportamento quando a condição for invertida ({clean_src}):\n"
            f"    result = {func_target}(...)\n"
            f"    self.assertNotEqual(result, unexpected_value)"
        )

    elif m_type == "ARITHMETIC":
        diagnosis = (
            f"A operação aritmética na linha {mutant.line_number} foi alterada de '{mutant.original_op}' para '{mutant.mutated_op}' "
            f"e a asserção do teste não percebeu a alteração numérica."
        )
        missing_scenario = (
            "O teste provavelmente usa valores triviais (como 0 ou 1) onde operações diferentes produzem o mesmo resultado, "
            "ou não realiza asserção sobre o valor exato calculado."
        )
        analogy = (
            "É como uma balança comercial que aceita qualquer peso porque o fiscal só verifica se tem algo em cima do prato, "
            "mas não confere se o valor em gramas está exato."
        )
        test_snippet = (
            f"def test_{func_target}_exact_arithmetic_value(self):\n"
            f"    # Valide o cálculo com valores não-triviais para matar mutante na linha {mutant.line_number}\n"
            f"    result = {func_target}(...)\n"
            f"    self.assertEqual(result, expected_exact_value)"
        )

    elif m_type == "BOOLEAN_CONSTANT":
        diagnosis = (
            f"A constante booleana na linha {mutant.line_number} foi invertida de '{mutant.original_op}' para '{mutant.mutated_op}' "
            f"sem que nenhum teste quebrasse."
        )
        missing_scenario = (
            f"Falta uma asserção semântica que verifique diretamente o efeito do sinalizador booleano ({mutant.original_op}) "
            f"no resultado final."
        )
        analogy = (
            "É como um disjuntor de segurança desligado na parede, mas a lâmpada continua ligada em outro fio "
            "e ninguém nota que o dispositivo de proteção está inoperante."
        )
        test_snippet = (
            f"def test_{func_target}_boolean_flag_effect(self):\n"
            f"    # Assegure que a flag '{mutant.original_op}' altera o comportamento do sistema\n"
            f"    result = {func_target}(...)\n"
            f"    self.assertTrue(result.flag_is_effective)"
        )

    elif m_type == "LOGICAL":
        diagnosis = (
            f"O operador lógico na linha {mutant.line_number} foi alterado de '{mutant.original_op}' para '{mutant.mutated_op}'. "
            f"As condições compostas não estão sendo testadas isoladamente."
        )
        missing_scenario = (
            "Falta um teste em tabela-verdade: teste o caso onde uma condição é Verdadeira e a outra é Falsa, "
            "e vice-versa."
        )
        analogy = (
            "É como uma porta de cofre que exige duas chaves simultâneas (A E B), mas ninguém testou se ela abre "
            "quando só uma das chaves é girada."
        )
        test_snippet = (
            f"def test_{func_target}_compound_logic_branches(self):\n"
            f"    # Teste os ramos intermediários da lógica '{mutant.original_op}'\n"
            f"    result = {func_target}(cond_a=True, cond_b=False)\n"
            f"    self.assertFalse(result.is_authorized)"
        )

    elif m_type == "RETURN_NULLIFICATION":
        diagnosis = (
            f"O comando 'return' na linha {mutant.line_number} foi substituído por 'return None' e o teste não falhou! "
            f"Seus testes chamam a função mas não conferem o valor retornado."
        )
        missing_scenario = (
            f"O teste invoca '{func_target}', mas não tem nenhuma asserção sobre o retorno "
            f"(apenas verifica que não deu erro ou exceção)."
        )
        analogy = (
            "É como pedir um prato no restaurante, o garçom voltar com a bandeja vazia e você pagar a conta "
            "sem reclamar porque 'ele não quebrou a louça'."
        )
        test_snippet = (
            f"def test_{func_target}_returns_valid_payload(self):\n"
            f"    # Assegure que o retorno não é nulo e contém os dados esperados\n"
            f"    result = {func_target}(...)\n"
            f"    self.assertIsNotNone(result)\n"
            f"    self.assertEqual(result, expected_payload)"
        )
    else:
        diagnosis = f"Mutante sobreviveu na linha {mutant.line_number} ({m_type})."
        missing_scenario = "Falta asserção semântica cobrindo esta instrução."
        analogy = "O teste atual é um oráculo superficial."
        test_snippet = (
            f"def test_{func_target}_assert_behavior(self):\n"
            f"    result = {func_target}(...)\n"
            f"    self.assertIsNotNone(result)"
        )

    return {
        "diagnosis": diagnosis,
        "missing_scenario": missing_scenario,
        "plain_language_analogy": analogy,
        "suggested_test_snippet": test_snippet
    }


def execute_mutation_analysis(
    target_file: Path,
    test_file_or_dir: Path,
    max_mutants: int = 15,
    timeout_sec: float = 20.0,
    covered_lines: Optional[Set[int]] = None,
    likely_equivalent: Optional[Dict[int, str]] = None,
    waivers: Optional[Dict[int, str]] = None,
) -> Dict[str, Any]:
    """Execute mutation testing against a single source file and its test suite."""
    target_file = target_file.resolve()
    test_file_or_dir = test_file_or_dir.resolve()

    if not target_file.is_file():
        return _attach_canonical_result({
            "status": "ERROR",
            "message": f"Target source file not found: {target_file}"
        }, target_file)

    original_code = target_file.read_text(encoding="utf-8", errors="replace")
    mutants = generate_mutants_for_source(original_code, max_mutants=max_mutants)

    if not mutants:
        return _attach_canonical_result({
            "status": "PASS",
            "target_file": str(target_file),
            "message": "No mutable AST sites found in target file.",
            "total_mutants": 0,
            "killed": 0,
            "survived": 0,
            "mutation_score": 100.0,
            "mutants": []
        }, target_file)

    # Determine working directory: common ancestor or repo root
    try:
        common_root = Path(os.path.commonpath([str(target_file), str(test_file_or_dir)]))
    except Exception:
        common_root = target_file.parent
    if common_root.is_file():
        common_root = common_root.parent

    # Build unittest command
    if test_file_or_dir.is_dir():
        baseline_cmd = [sys.executable, "-m", "unittest", "discover", "-s", str(test_file_or_dir)]
    else:
        baseline_cmd = [sys.executable, "-m", "unittest", str(test_file_or_dir)]

    run_env = os.environ.copy()
    run_env["PYTHONPATH"] = str(common_root) + os.pathsep + run_env.get("PYTHONPATH", "")

    # Verify baseline tests pass with original code first
    try:
        baseline_res = subprocess.run(
            baseline_cmd,
            capture_output=True,
            text=True,
            timeout=timeout_sec,
            cwd=common_root,
            env=run_env
        )
        if baseline_res.returncode != 0:
            return _attach_canonical_result({
                "status": "ERROR",
                "message": "Baseline test suite failed before mutation testing. Tests must be green first.",
                "baseline_stderr": baseline_res.stderr[:500]
            }, target_file)
    except Exception as exc:
        return _attach_canonical_result({
            "status": "ERROR",
            "message": f"Failed to execute baseline tests: {exc}"
        }, target_file)

    killed = 0
    survived = 0
    no_coverage = 0
    likely_equivalent_count = 0
    waived_count = 0
    timed_out = 0
    evaluator_errors = 0
    mutants_report = []
    remediations = []
    likely_equivalent = likely_equivalent or {}
    waivers = waivers or {}

    code_lines = original_code.splitlines()
    tree = None
    try:
        tree = ast.parse(original_code, filename=str(target_file))
    except Exception:
        tree = None

    # Run tests against each mutant by safe swap in place with try/finally restore
    try:
        for m in mutants:
            if covered_lines is not None and m.line_number not in covered_lines:
                m.status = "NO_COVERAGE"
                no_coverage += 1
            else:
                # Write mutant to target file only when the mutated line was observed
                # or when no independent coverage evidence was supplied.
                target_file.write_text(m.mutated_code, encoding="utf-8")

            try:
                if m.status == "NO_COVERAGE":
                    run_res = None
                else:
                    run_res = subprocess.run(
                        baseline_cmd,
                        capture_output=True,
                        text=True,
                        timeout=timeout_sec,
                        cwd=common_root,
                        env=run_env
                    )
                    if run_res.returncode != 0:
                        m.status = "KILLED"
                        killed += 1
                    else:
                        m.status = "SURVIVED"
                        survived += 1
            except subprocess.TimeoutExpired as exc:
                # A stalled evaluator is not evidence that the test suite killed the mutant.
                m.status = "TIMEOUT"
                m.error_output = str(exc)
                timed_out += 1
            except Exception as exc:
                # Evaluator failure must fail closed; never inflate the mutation score.
                m.status = "ERROR"
                m.error_output = str(exc)
                evaluator_errors += 1

            if m.status == "SURVIVED" and m.mutant_id in likely_equivalent:
                reason = str(likely_equivalent[m.mutant_id]).strip()
                if reason:
                    m.status = "LIKELY_EQUIVALENT"
                    m.disposition_reason = reason
                    survived -= 1
                    likely_equivalent_count += 1
            if m.status in {"SURVIVED", "NO_COVERAGE"} and m.mutant_id in waivers:
                reason = str(waivers[m.mutant_id]).strip()
                if reason:
                    if m.status in {"SURVIVED", "NO_COVERAGE"}:
                        survived -= 1
                    else:
                        no_coverage -= 1
                    m.status = "WAIVED"
                    m.disposition_reason = reason
                    waived_count += 1

            mutant_dict: Dict[str, Any] = {
                "mutant_id": m.mutant_id,
                "line": m.line_number,
                "type": m.mutation_type,
                "original": m.original_op,
                "mutated": m.mutated_op,
                "status": m.status,
                "criticality": m.criticality,
                "security_relevant": m.security_relevant,
                "covered": None if covered_lines is None else (m.line_number in covered_lines),
                "disposition_reason": m.disposition_reason,
                "error": m.error_output,
            }

            if m.status == "SURVIVED":
                src_line = code_lines[m.line_number - 1].strip() if 1 <= m.line_number <= len(code_lines) else ""
                enc_func = find_enclosing_function_name(tree, m.line_number)
                remediation = generate_remediation_prescription(m, src_line, enc_func)
                mutant_dict["remediation"] = remediation
                remediations.append({
                    "mutant_id": m.mutant_id,
                    "line": m.line_number,
                    "source_line": src_line,
                    "mutation_type": m.mutation_type,
                    "original_op": m.original_op,
                    "mutated_op": m.mutated_op,
                    **remediation
                })

            mutants_report.append(mutant_dict)
    finally:
        # Always guarantee original code is restored
        target_file.write_text(original_code, encoding="utf-8")

    total = len(mutants)
    score_denominator = killed + survived + no_coverage
    score = (killed / score_denominator * 100.0) if score_denominator > 0 else 100.0
    evaluated_mutants = total - timed_out - evaluator_errors
    execution_failed = timed_out > 0 or evaluator_errors > 0
    unresolved = survived + no_coverage

    return _attach_canonical_result({
        "status": "ERROR" if execution_failed else ("WARN" if unresolved > 0 else "PASS"),
        "target_file": str(target_file),
        "total_mutants": total,
        "evaluated_mutants": evaluated_mutants,
        "killed": killed,
        "survived": survived,
        "no_coverage": no_coverage,
        "likely_equivalent": likely_equivalent_count,
        "waived": waived_count,
        "timeouts": timed_out,
        "errors": evaluator_errors,
        "mutation_score": round(score, 1),
        "coverage_evidence_supplied": covered_lines is not None,
        "survived_mutants_detected": survived > 0,
        "vitiated_oracles_detected": survived > 0,
        "mutants": mutants_report,
        "remediations": remediations
    }, target_file)


def format_prescriptive_report(res: Dict[str, Any]) -> str:
    """Format an actionable, plain-language prescriptive report for terminal display."""
    target = res.get("target_file", "unknown")
    total = res.get("total_mutants", 0)
    killed = res.get("killed", 0)
    survived = res.get("survived", 0)
    score = res.get("mutation_score", 0.0)
    remediations = res.get("remediations", [])

    lines = [
        "=" * 80,
        "   AURA CODE -- AUDITORIA DE MUTAÇÃO AST & PRESCRIÇÃO DE CORREÇÃO",
        "=" * 80,
        f">> Arquivo Analisado: {target}",
        f">> Mutantes Totais: {total} | Eliminados (Killed): {killed} | Sobreviventes: {survived}",
        f">> Escore de Mutação: {score}%",
    ]

    if res.get("status") == "ERROR":
        lines.append(f"\n[STATUS: ERROR] Falha na execução da análise de mutação:")
        lines.append(f"   {res.get('message', 'Erro desconhecido')}")
        if res.get("baseline_stderr"):
            lines.append(f"   Stderr: {res['baseline_stderr']}")
        lines.append("=" * 80)
        return "\n".join(lines)

    if not remediations:
        lines.append("\n[STATUS: PASS] Nenhum oráculo viciado detectado! A suíte de testes exerceu as mutações com sucesso.")
        lines.append("=" * 80)
        return "\n".join(lines)

    lines.append(f"\n[ALERTA DE SEGURANÇA]: Foram detectados {len(remediations)} ORÁCULOS VICIADOS / FALSOS na suíte!")
    lines.append("A suíte não distinguiu uma ou mais alterações semânticas; isso pode indicar ausência de cobertura, oráculo fraco ou mutação equivalente.")
    lines.append("-" * 80)

    for idx, rem in enumerate(remediations, 1):
        lines.append(f"\n>> PRESCRIÇÃO DE CORREÇÃO #{idx} (Linha {rem.get('line', '?')})")
        lines.append(f"   Código Original: {rem.get('source_line', '')}")
        lines.append(f"   Operador Mutado: {rem.get('mutation_type', '')} ({rem.get('original_op', '')} -> {rem.get('mutated_op', '')})")
        lines.append(f"   Diagnóstico:     {rem.get('diagnosis', '')}")
        lines.append(f"   Cenário Ausente: {rem.get('missing_scenario', '')}")
        lines.append(f"   Analogia:        \"{rem.get('plain_language_analogy', '')}\"")
        lines.append("   Sugestão de Teste Unitário para Matar o Mutante:")
        snippet = rem.get("suggested_test_snippet", "")
        for sline in snippet.splitlines():
            lines.append(f"      {sline}")

    lines.append("\n" + "=" * 80)
    lines.append(">> AÇÃO RECOMENDADA: Adicione os testes sugeridos acima até o escore atingir 100%.")
    lines.append("=" * 80)
    return "\n".join(lines)


def main() -> None:
    args = sys.argv[1:]
    if not args or "--help" in args or "-h" in args:
        print("Usage: auracode tests --mutate <target_source_file> <test_file_or_dir> [--json]")
        sys.exit(0)

    use_json = "--json" in args
    clean_args = [a for a in args if not a.startswith("--")]
    target_src = Path(clean_args[0])
    test_target = Path(clean_args[1]) if len(clean_args) > 1 else Path("tests")

    res = execute_mutation_analysis(target_src, test_target)
    if use_json:
        print(json.dumps(res, indent=2, ensure_ascii=False))
    else:
        print(format_prescriptive_report(res))
    sys.exit(0 if res.get("status") in ("PASS", "WARN") else 1)


if __name__ == "__main__":
    main()
