#!/usr/bin/env python3
"""AuraCode Lightweight AST Mutation Engine.

Detects vitiated oracles and vacuous test suites generated by LLMs by introducing
deterministic syntactic mutations into production code and executing tests.
If tests pass despite logic alterations, the test suite is flagged as a vitiated oracle.
Zero external runtime dependencies (Pure Python Standard Library: ast, subprocess, tempfile).
"""

import ast
import copy
import json
import os
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import List, Tuple, Optional, Dict, Any


@dataclass
class Mutant:
    """Represents a discrete syntactic code mutation."""
    mutant_id: int
    line_number: int
    mutation_type: str
    original_op: str
    mutated_op: str
    mutated_code: str
    status: str = "PENDING"  # KILLED, SURVIVED, TIMEOUT, ERROR
    error_output: Optional[str] = None


class ASTMutantGenerator(ast.NodeTransformer):
    """Generates discrete mutants from a Python AST."""

    # Relational operator mappings
    RELATIONAL_MAP = {
        ast.Gt: ast.LtE,
        ast.Lt: ast.GtE,
        ast.GtE: ast.Lt,
        ast.LtE: ast.Gt,
        ast.Eq: ast.NotEq,
        ast.NotEq: ast.Eq,
    }

    # Arithmetic operator mappings
    ARITHMETIC_MAP = {
        ast.Add: ast.Sub,
        ast.Sub: ast.Add,
        ast.Mult: ast.FloorDiv,
    }

    # Boolean operator mappings
    BOOLOP_MAP = {
        ast.And: ast.Or,
        ast.Or: ast.And,
    }

    def __init__(self, target_node_index: int = -1):
        super().__init__()
        self.target_node_index = target_node_index
        self.current_index = 0
        self.mutated = False
        self.recorded_mutation: Optional[Tuple[int, str, str, str]] = None

    def visit_Compare(self, node: ast.Compare) -> ast.AST:
        new_ops = []
        for op in node.ops:
            op_type = type(op)
            if op_type in self.RELATIONAL_MAP:
                if self.current_index == self.target_node_index:
                    new_op_cls = self.RELATIONAL_MAP[op_type]
                    new_ops.append(new_op_cls())
                    self.mutated = True
                    self.recorded_mutation = (
                        node.lineno,
                        "RELATIONAL",
                        op_type.__name__,
                        new_op_cls.__name__
                    )
                else:
                    new_ops.append(op)
                self.current_index += 1
            else:
                new_ops.append(op)
        node.ops = new_ops
        return self.generic_visit(node)

    def visit_BinOp(self, node: ast.BinOp) -> ast.AST:
        op_type = type(node.op)
        if op_type in self.ARITHMETIC_MAP:
            if self.current_index == self.target_node_index:
                new_op_cls = self.ARITHMETIC_MAP[op_type]
                node.op = new_op_cls()
                self.mutated = True
                self.recorded_mutation = (
                    node.lineno,
                    "ARITHMETIC",
                    op_type.__name__,
                    new_op_cls.__name__
                )
            self.current_index += 1
        return self.generic_visit(node)

    def visit_BoolOp(self, node: ast.BoolOp) -> ast.AST:
        op_type = type(node.op)
        if op_type in self.BOOLOP_MAP:
            if self.current_index == self.target_node_index:
                new_op_cls = self.BOOLOP_MAP[op_type]
                node.op = new_op_cls()
                self.mutated = True
                self.recorded_mutation = (
                    node.lineno,
                    "LOGICAL",
                    op_type.__name__,
                    new_op_cls.__name__
                )
            self.current_index += 1
        return self.generic_visit(node)

    def visit_Constant(self, node: ast.Constant) -> ast.AST:
        if isinstance(node.value, bool):
            if self.current_index == self.target_node_index:
                node.value = not node.value
                self.mutated = True
                self.recorded_mutation = (
                    node.lineno,
                    "BOOLEAN_CONSTANT",
                    str(not node.value),
                    str(node.value)
                )
            self.current_index += 1
        return node

    def visit_Return(self, node: ast.Return) -> ast.AST:
        if node.value is not None and not (isinstance(node.value, ast.Constant) and node.value.value is None):
            if self.current_index == self.target_node_index:
                original_repr = ast.unparse(node.value) if hasattr(ast, "unparse") else "expr"
                node.value = ast.Constant(value=None)
                self.mutated = True
                self.recorded_mutation = (
                    node.lineno,
                    "RETURN_NULLIFICATION",
                    original_repr,
                    "None"
                )
            self.current_index += 1
        return self.generic_visit(node)


def generate_mutants_for_source(source_code: str, max_mutants: int = 25) -> List[Mutant]:
    """Parse source code and generate up to max_mutants discrete syntactic mutants."""
    try:
        base_tree = ast.parse(source_code)
    except SyntaxError:
        return []

    # Count total mutable locations
    counter = ASTMutantGenerator(target_node_index=-1)
    counter.visit(copy.deepcopy(base_tree))
    total_sites = counter.current_index

    mutants = []
    step = max(1, total_sites // max_mutants) if total_sites > max_mutants else 1
    selected_indices = list(range(0, total_sites, step))[:max_mutants]

    for m_id, idx in enumerate(selected_indices, start=1):
        mut_gen = ASTMutantGenerator(target_node_index=idx)
        mut_tree = mut_gen.visit(copy.deepcopy(base_tree))
        if mut_gen.mutated and mut_gen.recorded_mutation:
            line_no, m_type, orig_op, new_op = mut_gen.recorded_mutation
            try:
                mut_code = ast.unparse(mut_tree)
            except AttributeError:
                # Python < 3.9 fallback
                continue

            mutants.append(Mutant(
                mutant_id=m_id,
                line_number=line_no,
                mutation_type=m_type,
                original_op=orig_op,
                mutated_op=new_op,
                mutated_code=mut_code
            ))

    return mutants


def find_enclosing_function_name(tree: Optional[ast.AST], target_line: int) -> Optional[str]:
    """Find the function or method enclosing a given line number."""
    if not tree:
        return None
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            start = getattr(node, "lineno", 0)
            end = getattr(node, "end_lineno", start + 100)
            if start <= target_line <= end:
                return node.name
    return None


def generate_remediation_prescription(
    mutant: Mutant,
    source_line: str,
    enclosing_func: Optional[str] = None
) -> Dict[str, Any]:
    """Generate prescriptive plain-language diagnosis, analogy, and test snippet."""
    m_type = mutant.mutation_type
    func_target = enclosing_func if enclosing_func else "target_function"
    clean_src = source_line.strip()

    if m_type == "RELATIONAL":
        diagnosis = (
            f"O teste atual não valida o caminho alternativo da condição na linha {mutant.line_number}. "
            f"A inversão do operador '{mutant.original_op}' para '{mutant.mutated_op}' continuou passando verde."
        )
        missing_scenario = (
            f"Falta um teste com entrada que force a condição '{clean_src}' a avaliar para o resultado oposto "
            f"(cenário de contorno ou negação da regra)."
        )
        analogy = (
            "É como testar uma catraca de metrô passando apenas com o cartão válido, "
            "sem testar se a catraca realmente bloqueia quem tenta passar sem pagar."
        )
        test_snippet = (
            f"def test_{func_target}_boundary_condition(self):\n"
            f"    # Cenário de contorno para matar mutante na linha {mutant.line_number}\n"
            f"    # Valide o comportamento quando a condição for invertida ({clean_src}):\n"
            f"    result = {func_target}(...)\n"
            f"    self.assertNotEqual(result, unexpected_value)"
        )

    elif m_type == "ARITHMETIC":
        diagnosis = (
            f"A operação aritmética na linha {mutant.line_number} foi alterada de '{mutant.original_op}' para '{mutant.mutated_op}' "
            f"e a asserção do teste não percebeu a alteração numérica."
        )
        missing_scenario = (
            "O teste provavelmente usa valores triviais (como 0 ou 1) onde operações diferentes produzem o mesmo resultado, "
            "ou não realiza asserção sobre o valor exato calculado."
        )
        analogy = (
            "É como uma balança comercial que aceita qualquer peso porque o fiscal só verifica se tem algo em cima do prato, "
            "mas não confere se o valor em gramas está exato."
        )
        test_snippet = (
            f"def test_{func_target}_exact_arithmetic_value(self):\n"
            f"    # Valide o cálculo com valores não-triviais para matar mutante na linha {mutant.line_number}\n"
            f"    result = {func_target}(...)\n"
            f"    self.assertEqual(result, expected_exact_value)"
        )

    elif m_type == "BOOLEAN_CONSTANT":
        diagnosis = (
            f"A constante booleana na linha {mutant.line_number} foi invertida de '{mutant.original_op}' para '{mutant.mutated_op}' "
            f"sem que nenhum teste quebrasse."
        )
        missing_scenario = (
            f"Falta uma asserção semântica que verifique diretamente o efeito do sinalizador booleano ({mutant.original_op}) "
            f"no resultado final."
        )
        analogy = (
            "É como um disjuntor de segurança desligado na parede, mas a lâmpada continua ligada em outro fio "
            "e ninguém nota que o dispositivo de proteção está inoperante."
        )
        test_snippet = (
            f"def test_{func_target}_boolean_flag_effect(self):\n"
            f"    # Assegure que a flag '{mutant.original_op}' altera o comportamento do sistema\n"
            f"    result = {func_target}(...)\n"
            f"    self.assertTrue(result.flag_is_effective)"
        )

    elif m_type == "LOGICAL":
        diagnosis = (
            f"O operador lógico na linha {mutant.line_number} foi alterado de '{mutant.original_op}' para '{mutant.mutated_op}'. "
            f"As condições compostas não estão sendo testadas isoladamente."
        )
        missing_scenario = (
            "Falta um teste em tabela-verdade: teste o caso onde uma condição é Verdadeira e a outra é Falsa, "
            "e vice-versa."
        )
        analogy = (
            "É como uma porta de cofre que exige duas chaves simultâneas (A E B), mas ninguém testou se ela abre "
            "quando só uma das chaves é girada."
        )
        test_snippet = (
            f"def test_{func_target}_compound_logic_branches(self):\n"
            f"    # Teste os ramos intermediários da lógica '{mutant.original_op}'\n"
            f"    result = {func_target}(cond_a=True, cond_b=False)\n"
            f"    self.assertFalse(result.is_authorized)"
        )

    elif m_type == "RETURN_NULLIFICATION":
        diagnosis = (
            f"O comando 'return' na linha {mutant.line_number} foi substituído por 'return None' e o teste não falhou! "
            f"Seus testes chamam a função mas não conferem o valor retornado."
        )
        missing_scenario = (
            f"O teste invoca '{func_target}', mas não tem nenhuma asserção sobre o retorno "
            f"(apenas verifica que não deu erro ou exceção)."
        )
        analogy = (
            "É como pedir um prato no restaurante, o garçom voltar com a bandeja vazia e você pagar a conta "
            "sem reclamar porque 'ele não quebrou a louça'."
        )
        test_snippet = (
            f"def test_{func_target}_returns_valid_payload(self):\n"
            f"    # Assegure que o retorno não é nulo e contém os dados esperados\n"
            f"    result = {func_target}(...)\n"
            f"    self.assertIsNotNone(result)\n"
            f"    self.assertEqual(result, expected_payload)"
        )
    else:
        diagnosis = f"Mutante sobreviveu na linha {mutant.line_number} ({m_type})."
        missing_scenario = "Falta asserção semântica cobrindo esta instrução."
        analogy = "O teste atual é um oráculo superficial."
        test_snippet = (
            f"def test_{func_target}_assert_behavior(self):\n"
            f"    result = {func_target}(...)\n"
            f"    self.assertIsNotNone(result)"
        )

    return {
        "diagnosis": diagnosis,
        "missing_scenario": missing_scenario,
        "plain_language_analogy": analogy,
        "suggested_test_snippet": test_snippet
    }


def execute_mutation_analysis(
    target_file: Path,
    test_file_or_dir: Path,
    max_mutants: int = 15,
    timeout_sec: float = 20.0
) -> Dict[str, Any]:
    """Execute mutation testing against a single source file and its test suite."""
    target_file = target_file.resolve()
    test_file_or_dir = test_file_or_dir.resolve()

    if not target_file.is_file():
        return {
            "status": "ERROR",
            "message": f"Target source file not found: {target_file}"
        }

    original_code = target_file.read_text(encoding="utf-8", errors="replace")
    mutants = generate_mutants_for_source(original_code, max_mutants=max_mutants)

    if not mutants:
        return {
            "status": "PASS",
            "target_file": str(target_file),
            "message": "No mutable AST sites found in target file.",
            "total_mutants": 0,
            "killed": 0,
            "survived": 0,
            "mutation_score": 100.0,
            "mutants": []
        }

    # Determine working directory: common ancestor or repo root
    try:
        common_root = Path(os.path.commonpath([str(target_file), str(test_file_or_dir)]))
    except Exception:
        common_root = target_file.parent
    if common_root.is_file():
        common_root = common_root.parent

    # Build unittest command
    if test_file_or_dir.is_dir():
        baseline_cmd = [sys.executable, "-m", "unittest", "discover", "-s", str(test_file_or_dir)]
    else:
        baseline_cmd = [sys.executable, "-m", "unittest", str(test_file_or_dir)]

    run_env = os.environ.copy()
    run_env["PYTHONPATH"] = str(common_root) + os.pathsep + run_env.get("PYTHONPATH", "")

    # Verify baseline tests pass with original code first
    try:
        baseline_res = subprocess.run(
            baseline_cmd,
            capture_output=True,
            text=True,
            timeout=timeout_sec,
            cwd=common_root,
            env=run_env
        )
        if baseline_res.returncode != 0:
            return {
                "status": "ERROR",
                "message": "Baseline test suite failed before mutation testing. Tests must be green first.",
                "baseline_stderr": baseline_res.stderr[:500]
            }
    except Exception as exc:
        return {
            "status": "ERROR",
            "message": f"Failed to execute baseline tests: {exc}"
        }

    killed = 0
    survived = 0
    timed_out = 0
    evaluator_errors = 0
    mutants_report = []
    remediations = []

    code_lines = original_code.splitlines()
    tree = None
    try:
        tree = ast.parse(original_code, filename=str(target_file))
    except Exception:
        tree = None

    # Run tests against each mutant by safe swap in place with try/finally restore
    try:
        for m in mutants:
            # Write mutant to target file
            target_file.write_text(m.mutated_code, encoding="utf-8")

            try:
                run_res = subprocess.run(
                    baseline_cmd,
                    capture_output=True,
                    text=True,
                    timeout=timeout_sec,
                    cwd=common_root,
                    env=run_env
                )
                if run_res.returncode != 0:
                    m.status = "KILLED"
                    killed += 1
                else:
                    m.status = "SURVIVED"
                    survived += 1
            except subprocess.TimeoutExpired as exc:
                # A stalled evaluator is not evidence that the test suite killed the mutant.
                m.status = "TIMEOUT"
                m.error_output = str(exc)
                timed_out += 1
            except Exception as exc:
                # Evaluator failure must fail closed; never inflate the mutation score.
                m.status = "ERROR"
                m.error_output = str(exc)
                evaluator_errors += 1

            mutant_dict: Dict[str, Any] = {
                "mutant_id": m.mutant_id,
                "line": m.line_number,
                "type": m.mutation_type,
                "original": m.original_op,
                "mutated": m.mutated_op,
                "status": m.status,
                "error": m.error_output,
            }

            if m.status == "SURVIVED":
                src_line = code_lines[m.line_number - 1].strip() if 1 <= m.line_number <= len(code_lines) else ""
                enc_func = find_enclosing_function_name(tree, m.line_number)
                remediation = generate_remediation_prescription(m, src_line, enc_func)
                mutant_dict["remediation"] = remediation
                remediations.append({
                    "mutant_id": m.mutant_id,
                    "line": m.line_number,
                    "source_line": src_line,
                    "mutation_type": m.mutation_type,
                    "original_op": m.original_op,
                    "mutated_op": m.mutated_op,
                    **remediation
                })

            mutants_report.append(mutant_dict)
    finally:
        # Always guarantee original code is restored
        target_file.write_text(original_code, encoding="utf-8")

    evaluated = killed + survived
    total = evaluated + timed_out + evaluator_errors
    score = (killed / evaluated * 100.0) if evaluated > 0 else 0.0
    passed = survived == 0 or score >= 75.0
    execution_failed = timed_out > 0 or evaluator_errors > 0

    return {
        "status": "ERROR" if execution_failed else ("PASS" if passed else "WARN"),
        "target_file": str(target_file),
        "total_mutants": total,
        "evaluated_mutants": evaluated,
        "killed": killed,
        "survived": survived,
        "timeouts": timed_out,
        "errors": evaluator_errors,
        "mutation_score": round(score, 1),
        "vitiated_oracles_detected": survived > 0,
        "mutants": mutants_report,
        "remediations": remediations
    }


def format_prescriptive_report(res: Dict[str, Any]) -> str:
    """Format an actionable, plain-language prescriptive report for terminal display."""
    target = res.get("target_file", "unknown")
    total = res.get("total_mutants", 0)
    killed = res.get("killed", 0)
    survived = res.get("survived", 0)
    score = res.get("mutation_score", 0.0)
    remediations = res.get("remediations", [])

    lines = [
        "=" * 80,
        "   AURA CODE -- AUDITORIA DE MUTAÇÃO AST & PRESCRIÇÃO DE CORREÇÃO",
        "=" * 80,
        f">> Arquivo Analisado: {target}",
        f">> Mutantes Totais: {total} | Eliminados (Killed): {killed} | Sobreviventes: {survived}",
        f">> Escore de Mutação: {score}%",
    ]

    if res.get("status") == "ERROR":
        lines.append(f"\n[STATUS: ERROR] Falha na execução da análise de mutação:")
        lines.append(f"   {res.get('message', 'Erro desconhecido')}")
        if res.get("baseline_stderr"):
            lines.append(f"   Stderr: {res['baseline_stderr']}")
        lines.append("=" * 80)
        return "\n".join(lines)

    if not remediations:
        lines.append("\n[STATUS: PASS] Nenhum oráculo viciado detectado! A suíte de testes exerceu as mutações com sucesso.")
        lines.append("=" * 80)
        return "\n".join(lines)

    lines.append(f"\n[ALERTA DE SEGURANÇA]: Foram detectados {len(remediations)} ORÁCULOS VICIADOS / FALSOS na suíte!")
    lines.append("Os testes atuais continuam 'verdes' mesmo quando o código produtivo tem sua lógica invertida.")
    lines.append("-" * 80)

    for idx, rem in enumerate(remediations, 1):
        lines.append(f"\n>> PRESCRIÇÃO DE CORREÇÃO #{idx} (Linha {rem.get('line', '?')})")
        lines.append(f"   Código Original: {rem.get('source_line', '')}")
        lines.append(f"   Operador Mutado: {rem.get('mutation_type', '')} ({rem.get('original_op', '')} -> {rem.get('mutated_op', '')})")
        lines.append(f"   Diagnóstico:     {rem.get('diagnosis', '')}")
        lines.append(f"   Cenário Ausente: {rem.get('missing_scenario', '')}")
        lines.append(f"   Analogia:        \"{rem.get('plain_language_analogy', '')}\"")
        lines.append("   Sugestão de Teste Unitário para Matar o Mutante:")
        snippet = rem.get("suggested_test_snippet", "")
        for sline in snippet.splitlines():
            lines.append(f"      {sline}")

    lines.append("\n" + "=" * 80)
    lines.append(">> AÇÃO RECOMENDADA: Adicione os testes sugeridos acima até o escore atingir 100%.")
    lines.append("=" * 80)
    return "\n".join(lines)


def main() -> None:
    args = sys.argv[1:]
    if not args or "--help" in args or "-h" in args:
        print("Usage: auracode tests --mutate <target_source_file> <test_file_or_dir> [--json]")
        sys.exit(0)

    use_json = "--json" in args
    clean_args = [a for a in args if not a.startswith("--")]
    target_src = Path(clean_args[0])
    test_target = Path(clean_args[1]) if len(clean_args) > 1 else Path("tests")

    res = execute_mutation_analysis(target_src, test_target)
    if use_json:
        print(json.dumps(res, indent=2, ensure_ascii=False))
    else:
        print(format_prescriptive_report(res))
    sys.exit(0 if res.get("status") in ("PASS", "WARN") else 1)


if __name__ == "__main__":
    main()
