#!/usr/bin/env python3
"""AuraCode Lightweight AST Mutation Engine.

Detects vitiated oracles and vacuous test suites generated by LLMs by introducing
deterministic syntactic mutations into production code and executing tests.
If tests pass despite logic alterations, the test suite is flagged as a vitiated oracle.
Zero external runtime dependencies (Pure Python Standard Library: ast, subprocess, tempfile).
"""

import ast
import copy
import json
import os
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import List, Tuple, Optional, Dict, Any


@dataclass
class Mutant:
    """Represents a discrete syntactic code mutation."""
    mutant_id: int
    line_number: int
    mutation_type: str
    original_op: str
    mutated_op: str
    mutated_code: str
    status: str = "PENDING"  # KILLED, SURVIVED, TIMEOUT, ERROR
    error_output: Optional[str] = None


class ASTMutantGenerator(ast.NodeTransformer):
    """Generates discrete mutants from a Python AST."""

    # Relational operator mappings
    RELATIONAL_MAP = {
        ast.Gt: ast.LtE,
        ast.Lt: ast.GtE,
        ast.GtE: ast.Lt,
        ast.LtE: ast.Gt,
        ast.Eq: ast.NotEq,
        ast.NotEq: ast.Eq,
    }

    # Arithmetic operator mappings
    ARITHMETIC_MAP = {
        ast.Add: ast.Sub,
        ast.Sub: ast.Add,
        ast.Mult: ast.FloorDiv,
    }

    # Boolean operator mappings
    BOOLOP_MAP = {
        ast.And: ast.Or,
        ast.Or: ast.And,
    }

    def __init__(self, target_node_index: int = -1):
        super().__init__()
        self.target_node_index = target_node_index
        self.current_index = 0
        self.mutated = False
        self.recorded_mutation: Optional[Tuple[int, str, str, str]] = None

    def visit_Compare(self, node: ast.Compare) -> ast.AST:
        new_ops = []
        for op in node.ops:
            op_type = type(op)
            if op_type in self.RELATIONAL_MAP:
                if self.current_index == self.target_node_index:
                    new_op_cls = self.RELATIONAL_MAP[op_type]
                    new_ops.append(new_op_cls())
                    self.mutated = True
                    self.recorded_mutation = (
                        node.lineno,
                        "RELATIONAL",
                        op_type.__name__,
                        new_op_cls.__name__
                    )
                else:
                    new_ops.append(op)
                self.current_index += 1
            else:
                new_ops.append(op)
        node.ops = new_ops
        return self.generic_visit(node)

    def visit_BinOp(self, node: ast.BinOp) -> ast.AST:
        op_type = type(node.op)
        if op_type in self.ARITHMETIC_MAP:
            if self.current_index == self.target_node_index:
                new_op_cls = self.ARITHMETIC_MAP[op_type]
                node.op = new_op_cls()
                self.mutated = True
                self.recorded_mutation = (
                    node.lineno,
                    "ARITHMETIC",
                    op_type.__name__,
                    new_op_cls.__name__
                )
            self.current_index += 1
        return self.generic_visit(node)

    def visit_BoolOp(self, node: ast.BoolOp) -> ast.AST:
        op_type = type(node.op)
        if op_type in self.BOOLOP_MAP:
            if self.current_index == self.target_node_index:
                new_op_cls = self.BOOLOP_MAP[op_type]
                node.op = new_op_cls()
                self.mutated = True
                self.recorded_mutation = (
                    node.lineno,
                    "LOGICAL",
                    op_type.__name__,
                    new_op_cls.__name__
                )
            self.current_index += 1
        return self.generic_visit(node)

    def visit_Constant(self, node: ast.Constant) -> ast.AST:
        if isinstance(node.value, bool):
            if self.current_index == self.target_node_index:
                node.value = not node.value
                self.mutated = True
                self.recorded_mutation = (
                    node.lineno,
                    "BOOLEAN_CONSTANT",
                    str(not node.value),
                    str(node.value)
                )
            self.current_index += 1
        return node

    def visit_Return(self, node: ast.Return) -> ast.AST:
        if node.value is not None and not (isinstance(node.value, ast.Constant) and node.value.value is None):
            if self.current_index == self.target_node_index:
                original_repr = ast.unparse(node.value) if hasattr(ast, "unparse") else "expr"
                node.value = ast.Constant(value=None)
                self.mutated = True
                self.recorded_mutation = (
                    node.lineno,
                    "RETURN_NULLIFICATION",
                    original_repr,
                    "None"
                )
            self.current_index += 1
        return self.generic_visit(node)


def generate_mutants_for_source(source_code: str, max_mutants: int = 25) -> List[Mutant]:
    """Parse source code and generate up to max_mutants discrete syntactic mutants."""
    try:
        base_tree = ast.parse(source_code)
    except SyntaxError:
        return []

    # Count total mutable locations
    counter = ASTMutantGenerator(target_node_index=-1)
    counter.visit(copy.deepcopy(base_tree))
    total_sites = counter.current_index

    mutants = []
    step = max(1, total_sites // max_mutants) if total_sites > max_mutants else 1
    selected_indices = list(range(0, total_sites, step))[:max_mutants]

    for m_id, idx in enumerate(selected_indices, start=1):
        mut_gen = ASTMutantGenerator(target_node_index=idx)
        mut_tree = mut_gen.visit(copy.deepcopy(base_tree))
        if mut_gen.mutated and mut_gen.recorded_mutation:
            line_no, m_type, orig_op, new_op = mut_gen.recorded_mutation
            try:
                mut_code = ast.unparse(mut_tree)
            except AttributeError:
                # Python < 3.9 fallback
                continue

            mutants.append(Mutant(
                mutant_id=m_id,
                line_number=line_no,
                mutation_type=m_type,
                original_op=orig_op,
                mutated_op=new_op,
                mutated_code=mut_code
            ))

    return mutants


def execute_mutation_analysis(
    target_file: Path,
    test_file_or_dir: Path,
    max_mutants: int = 15,
    timeout_sec: float = 6.0
) -> Dict[str, Any]:
    """Execute mutation testing against a single source file and its test suite."""
    target_file = target_file.resolve()
    test_file_or_dir = test_file_or_dir.resolve()

    if not target_file.is_file():
        return {
            "status": "ERROR",
            "message": f"Target source file not found: {target_file}"
        }

    original_code = target_file.read_text(encoding="utf-8", errors="replace")
    mutants = generate_mutants_for_source(original_code, max_mutants=max_mutants)

    if not mutants:
        return {
            "status": "PASS",
            "message": "No mutable AST sites found in target file.",
            "total_mutants": 0,
            "killed": 0,
            "survived": 0,
            "mutation_score": 100.0,
            "mutants": []
        }

    # Determine working directory: common ancestor or repo root
    try:
        common_root = Path(os.path.commonpath([str(target_file), str(test_file_or_dir)]))
    except Exception:
        common_root = target_file.parent
    if common_root.is_file():
        common_root = common_root.parent

    # Build unittest command
    if test_file_or_dir.is_dir():
        baseline_cmd = [sys.executable, "-m", "unittest", "discover", "-s", str(test_file_or_dir)]
    else:
        baseline_cmd = [sys.executable, "-m", "unittest", str(test_file_or_dir)]

    run_env = os.environ.copy()
    run_env["PYTHONPATH"] = str(common_root) + os.pathsep + run_env.get("PYTHONPATH", "")

    # Verify baseline tests pass with original code first
    try:
        baseline_res = subprocess.run(
            baseline_cmd,
            capture_output=True,
            text=True,
            timeout=timeout_sec,
            cwd=common_root,
            env=run_env
        )
        if baseline_res.returncode != 0:
            return {
                "status": "ERROR",
                "message": "Baseline test suite failed before mutation testing. Tests must be green first.",
                "baseline_stderr": baseline_res.stderr[:500]
            }
    except Exception as exc:
        return {
            "status": "ERROR",
            "message": f"Failed to execute baseline tests: {exc}"
        }

    killed = 0
    survived = 0
    mutants_report = []

    # Run tests against each mutant by safe swap in place with try/finally restore
    try:
        for m in mutants:
            # Write mutant to target file
            target_file.write_text(m.mutated_code, encoding="utf-8")

            try:
                run_res = subprocess.run(
                    baseline_cmd,
                    capture_output=True,
                    text=True,
                    timeout=timeout_sec,
                    cwd=common_root,
                    env=run_env
                )
                if run_res.returncode != 0:
                    m.status = "KILLED"
                    killed += 1
                else:
                    m.status = "SURVIVED"
                    survived += 1
            except subprocess.TimeoutExpired:
                m.status = "KILLED"  # Timeout is considered killed by infinite loop/stall
                killed += 1
            except Exception as e:
                m.status = "KILLED"
                killed += 1

            mutants_report.append({
                "mutant_id": m.mutant_id,
                "line": m.line_number,
                "type": m.mutation_type,
                "original": m.original_op,
                "mutated": m.mutated_op,
                "status": m.status
            })
    finally:
        # Always guarantee original code is restored
        target_file.write_text(original_code, encoding="utf-8")

    total = killed + survived
    score = (killed / total * 100.0) if total > 0 else 100.0
    passed = survived == 0 or score >= 75.0

    return {
        "status": "PASS" if passed else "WARN",
        "target_file": str(target_file),
        "total_mutants": total,
        "killed": killed,
        "survived": survived,
        "mutation_score": round(score, 1),
        "vitiated_oracles_detected": survived > 0,
        "mutants": mutants_report
    }


def main() -> None:
    args = sys.argv[1:]
    if not args or "--help" in args or "-h" in args:
        print("Usage: auracode tests --mutate <target_source_file> <test_file_or_dir>")
        sys.exit(0)

    target_src = Path(args[0])
    test_target = Path(args[1]) if len(args) > 1 else Path("tests")

    res = execute_mutation_analysis(target_src, test_target)
    print(json.dumps(res, indent=2))
    sys.exit(0 if res.get("status") == "PASS" else 1)


if __name__ == "__main__":
    main()
